---
- name: Create Gitea folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/gitea"
    state: directory
    mode: 0755
  become: false

- name: Copy Gitea docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/gitea-docker-compose.yml.j2
    dest: "{{ config_dir }}/gitea/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart gitea

- name: Ensure Gitea is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/gitea/"
    build: false
  become: false
