---
- name: Create vaultwarden folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/vaultwarden"
    state: directory
    mode: 0755
  become: false

- name: Copy caddy config file
  ansible.buitin.copy:
    src: files/Caddyfile
    dest: "{{ config_dir }}/vaultwarden/Caddyfile"

- name: Copy vaultwarden docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/vaultwarden-docker-compose.yml.j2
    dest: "{{ config_dir }}/vaultwarden/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart vaultwarden

- name: Ensure vaultwarden is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/vaultwarden/"
    build: false
  become: false
