---
- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
  when: ansible_facts.os_family == "Debian"

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
  when: ansible_facts.os_family == "Debian"

- name: Restart nmb
  ansible.builtin.service:
    name: nmbd
    state: restarted

- name: Restart smb
  ansible.builtin.service:
    name: smbd
    state: restarted
